---
title: "Reflection"
---

**Self Reflection NEW:**

As I went through the extra lesson plans, I noticed that it had began to get more difficult to keep a plan and general path of how the class should be taught. The beginning of the class is introducing base statistics concepts and ideas, so presenting those is fairly straightforward, but as you get to further inference ideas, how you organize the class begins to get complicated.

For example, one idea I had/have is to organize the class in term of how you attack a problem, with defining the data type for the explanatory and response variables near the beginning. In this system, you would have a table of (originally, but now there is more than 4) "quadrants" with one axis of the table being your response and the other being the explanatory. It would look something like this:

|             |                                |                     |
|-------------|--------------------------------|---------------------|
|             | Categorical                    | Quant               |
| Categorical | (categorical response section) | logistic regression |
| Quant       | t test/f test                  | linear regression   |

Note: I now have a category for dichotomous so its actually a 3x3 not a 2x2

We wouldn't cover the whole table, but it would ideally help them organize what they are learning and how to approach statistical problems as well as what they could learn in the future.

While I may use this table as a reminder, I currently do not have the whole class set up with this system. It is an ongoing project, but I have been going back and fourth with organization strategies for a while now.

There are so many ways to teach, so deciding on what to do, in my opinion, is much harder than planning single lesson.

I also was unsure what to include as a whole. I did have other classes to use as a roadmap, but there are some things that I felt needed to be changed and added. This ended up with a (currently) messy and idealistic plan, and my definition for "days" have decayed into a loose idea that i section lessons around. Days no longer actually describe a section of time but more so some kind of ordinal data where 1 day means a bit of time and 3 days means a bit of time longer than 1 day but an unknown amount of total time.

A difficult aspect of lesson planning lies ahead, as I will have to go through and reorganize the entire plan, as well as decide what needs cut and what can be set as a "stretch goal" for filler time. I plan to do this task once all weeks are complete so I do not have to do it twice.

I anticipate quite a bit of changes, but I may plan optimistically so that I can tune things as the class goes on. I plan to do this by having urgent sections, ideal review times of those sections, side importance sections, and filler sections. As the class goes on, if an urgent piece of material needs more review, more time will be spent on it. I will then use any extra time to cover side importance and filler sections. This will allow me to cover all that is necessary to a satisfactory extent and then go forward on other topics. As for how I was going to gauge satisfactory understanding, I was considering a threshold system where students would be assessed and this would (secretly) determine if the topic lasted longer or not, extended within reason. I could also track the performance of urgent materials, and then use review days to flash back to those topics. In my experience, sometimes you don't understand something until it is fully complete and then reviewed later, so i may have an unordered way of doing review to ensure that they are understanding the topic. Exams and projects should ideally call back to previous material in some way so the older material is worth looking into. So the lectures may go back and forth between old and new material so that the class can fully understand the topics as well as make absences less dire. If everything is done well this should allow me to dynamically plan the class so that all topics can be covered and given adequate attention.

So going forward, I think I will use a new system where topics are split into the basics, review, and optional additional material and bonus topics are labeled specifically. When teaching, I will prioritize the urgent topics and prep for further topics to have the maximum expected extra time needed (planning for the worst case realistic situation), and then other topics will be put in bonus day categories. This will likely result in the beginning of the class being dedicated to core material with review days every so often, with the material deviating more as the course goes on, with more bonus/filler days available, as well as more days where we review old material again with new aspects attached.

\<topic\>\<classification\>\<expected review multiplier\>

priority order {urgent introduction, urgent review (may or may not be deleted depending on performance/receptions), side topic, side topic review (may or may not be deleted depending on performance/receptions), bonus/fun days}

I will give two examples: introducing p values is difficult and very important, so I will place that in the urgent and expected to need many review sessions. Confounding variables is also important, but I think understanding the topic will be less of a struggle, so there will not be as many worst-case-scenario-reviews-planned

**Self Reflection:**

After typing the below text, I have decided to put the self reflection at the top.

I feel like I have added a fair amount of information on this site, and I am happy that I was able to get some of it working (except the github hosting aspect). I like a lot of whats on here, but I still see the project as far from finished, even when not including the upcoming weeks.

I would like to add more detail to the assessments, to the point where they are all independent files like the handouts. I would also like to improve the aesthetics of it all, as a lot of the formatting fell flat (for example, the code chunks are NOT supposed to be visible as that is just distracting.

Overall, while I am proud of the information on here and the fact that this is my first quarto site, I still see many avenues for improvement, and I plan to attend office hours to improve some of the more technical issues I have faced.

------------------------------------------------------------------------

The following entry is a combination of my reflection and methods for the class. I think about class design a lot so the methods I would like to employ are deeply related to the ideas on how the class should be structured.

Every class has core ideas, so I have decided to plan the class around a few central themes. These ideas will be introduced early on, and then referenced regularly throughout the class:

-   Visual statistics

    -   Statistics can be much easier to have an intuition for when visuals are provided, so the class will make frequent use of graphs and colors along side formulas and concepts. (This will require a bit of set theory to begin)

-   lack of words

    -   Math is harder with words, and sometimes words can prevent a deeper understanding of a topic. I would like to frequently give students information and questions that feature very little words or hard data, and instead require them to visually asses the problem

    -   This also applies to labeled formulas. Eventually, I would like to prepare annotated formulas that use as few words as practical. Mindlessly using formulas is not good, but sometimes a labeled formula can help build a conceptual understanding if the elements are considered closely by the reader.

-   dice and spinners

    -   probability distributions are abstract, but everyone knows how dice and spinners work, I would like to regularly reference these when discussing probability distributions.

-   "numbers do not speak for themselves"

    -   Without assumptions in place, statistics can be very subjective (as is math in general). I want to regularly encourage students to interpret the data themselves when no assumptions are provided, and stress how many aspects of statistics are subjective.

-   vocab is vocab

    -   Sometimes theirs no replacement for just reading and understanding vocab. This will be given to them directly rather than hoping the correct definitions are gathered from discussion alone.

-   Slides not the focus

    -   There will be some use of slides in class used to paste some visual ideas in front of the class, but they will not be consistently up. Often times words on slides can detract from the topic, so the slides will not have much text information on them. To maintain pace and engagement, I would prefer to use an overhead or board to perform methods in class, and physical methods performed on the spot will be preferred to slides.

    -   In my own lectures, I have notices that I tend to disconnect the slideshow frequently to display simulations and write on the board/overhead. So demonstrations will be prioritized to slides.

-   clear expectation

    -   While I would love students to be so interested in the course that they start watching 3blue1brown videos and learn things that I haven't even mentioned, this does not feel realistic. My goal is for students to know what concepts to understand and how to train them. I will ask some challenge questions, but they will be graded as more of a bonus and gauge of engagement and ability rather than a requirement.

With exams, there are a few methods I am interested to investigate

-   exam independent of time

    -   While I believe that everything in the course will be planned so that, with sufficient hard work, every student will be able to understand and answer correctly, I've always felt that time doesn't effect everyone the same. Some students approach exams with a ton panic, others check their work more than others, some students accidentally get hung up on a question, these kinda traits can make some students do worse on time tests than others even if they don't have a contrition recognized by the SSD. To ease this aspect and hopefully make the learning less stressful I would like to figure out a way to make tests have such ample time that students don't think about it (within reason). I don't want the test to be less challenging, just challenging in the understanding of materials of materials way and not challenging in a resistance to panic way.

    -   In a perfect world, I would have a room that I could rent for a few hours and have closed book proctored tests

-   Competency and Challenge

    -   Tests serve two functions: to measure general competency and to gauge how well the class is absorbing the materials. Both aspects are useful: If I were to only gauge competency, I would not know when to speed up or slow down, and if I were to only gauge ability on a relative scale, this would miss the main point of the class: to produce competent readers of data. An idea I would like to investigate on exams, is to have high weighted competency section and a lesser weighted/bonus challenge section (this will likely not be formally stated in the test). This allows me to grade primarily on competency, and that students who display competency get a good grade, but also lets me see how the class is doing and if students have taken a special interest in statistics. I think of this like a skewed distribution where the competency (hopefully the median) is centered around the higher percentages, but the the distribution quickly drops down and the density at 100% is near 0.

I personally believe that final projects are generally more effective than final exams, as many undergrad final projects have given me information and experience that I still find important years later, so the final will be project based:

-   The final project will be in three parts: presentation, paper, assessment and reflection\\

-   The presentation will happen first during the week before finals. Students will be given reactions on how to improve anything wrong with the information so far.

-   The paper will be submitted during finals week. This will have more in depth information and be graded to a more exact standard

-   The reflection will be a combination of students attending and reacting to other presentations, along with reflecting on their experience working as a group.

The class will feature many activities based on participation, with the following main goals. Activities in class will be on the spot and not require to pre reading to understand. Ideally, the handouts and introduction lecture should cover it.

-   Activities allow students to confront ideas with each other to learn them

-   Activities give students an opportunity to question ideas layed out in class (it is near impossible not to miss something when teaching, so if I get successfully (and politely) called out on something during an activity, I will consider it to be a teaching win.

-   Activities are not just for completing work, Ideally, they will be structured so that students feel more comfortable expressing ideas openly and to each other. if student are too rigid, they may find engaging in class to be too nerve racking as they feel judged by strangers. In practice, I will not get at them for discussing topics that aren't immediately math related (within reason).

There will also be demonstrations, but these demonstrations will be used as a means to deliver information on methods that are particularly confusing, or display activities that would take a large amount of classroom

-   For example, there is a demonstration I do where I calculate the P value using colored squares and clear paper. This could be performed in class but it could be demonstrated as a demonstration in much less time (I have noticed that time can be a huge challenge so I intend to have backups and compensating actions for if things do not go as fast as planned)

Homework will have the following ideas in its design:

-   Homework will be very short and frequent. This is to avoid all the problems with stressful cramming and encourage learning little by little. Homework will be assigned after the material is began and they will have until the lecture after the lecture after the section is completed.

-   Homework should straight forward and avoid situations where these student has no idea how to even look for an answer. All homework questions will related directly to on canvas materials. If the student gives themselves the proper time. the learning process should be calm.

-   Most of the homework questions will be nigh-objective in correct answers, but to encourage free thinking and engagement there will always be a creative question they are to answer, which is graded more on submission. This is to encourage them to take a risk and attempt at reorganizing what they learned, without being penalized for not copying definitions exactly. If they make flawed assumptions, they will be notified about it, but it will not harm their grade.

This plan is already feeling very optimistic, but I have a few even more optimistic stretch goals:

-   Homework and projects will not just have context, but a consistent narrative. A prime example of narrative in homework is the *Murder in SQL City* assignment. Aside from being fun, I am willing to be that narrative aspects can increase engagement and understanding.

-   Students will be given intentionally subjective questions in class, which they will discuss with others and hopefully (politely lightheartedly) debate each other.

-   SUPER STRETCH GOAL: if by some wild circumstances I end up being am inhumanly efficient teacher and the class goes exceptionally, I would love to briefly mention a little bit of R. Programming basics are extremely useful and I have benefit tremendously from the classes that included it. Realistically, this would be very basic stuff, more realistically, we will not have time, but I like having optimistic stretch goals regardless.
