---
title: "PLANDOCDAY6"
---

## DAY6

------------------------------------------------------------------------

Significance: 50 minutes

**Objectives:**

> Students understand that the null distribution is separate from the data collected
>
> Students know how to use simulations to find p value
>
> Students know what symbols relate to the statistic and parameter
>
> Students can write a hypothesis statement with symbols
>
> Students can correctly differentiate between a p value and a p hat value ( a very common issue I noticed in exams )
>
> Students understand that significance standards can be changed

**Concepts:**

> Review: Population and Sample
>
> Review: data types
>
> The block (symbols for population parameters and sample stats)
>
> DISTINCT Null distribution
>
> DISTINCT alternative space
>
> "significance" How weird/percent match
>
> hypothesis symbols format
>
> P value vs P hat
>
> "infinite sample mode"

**Intuition Tools:**

> P value as colors/area
>
> P value as conditional probability
>
> P value as percent match

**Lesson Material:**

To begin the lesson, we will go over a problem: how weird is the dolphin result (except we will use a 4 sample test instead of a 16 sample test so it is easier to count)

Given that the dolphins succeeded 4/4 times, how abnormal is that?

To answer the question, we will first simulate a distribution if the dolphins were acting randomly, then print it out on clear paper.

This is our null distribution

NUL DISTRIBUTION: probability distribution assuming the null hypothesis is true.

Then we will then graph an area on clear paper that encompasses all xvalues over 4.

This is out alternative space

ALTERNATIVE SPACE: this is a term I use to describe the area you are questioning for the alternative hypothesis

After constructing these two graphs, we will then overlay them to see how much they line up, and apply the same conditional probability logic as before. After testing counting the green squares, 1, vs the amount of total blue squares 16, we can see that this event would have a 1/16 =0.0625 chance of happenng.

This is the p value

PVALUE: Proportion of successive experiments resulting in an outcome assuming the null is true

So if the null is true, such an outcome only has a 6.25% chance of happening in the experiment.

Is this a weird result?

Lets think about it.

I will then ask the class to answer, in general, if 5% is a lot. They will probably give nuanced answers about how it depends on the circumstances, but I will request a yes or no answer.

This exercise is to point out that significance is subjective and can change.

While this is up to some interpretation, I will then tell them that the significance requirement will be provided on exams unless it is a concept question, and any answer about significance is valid if the calculations are correct and the only difference is the interpretation.

We will then jump to the 16 count dolphin example to gather more data. A simulation will be ran, and the counts will be performed automatically.

Once performed, the P value will be about 0.003 or 0.03%, I will then ask the class to raise their hand to indicate if this is significant. Regardless of the class answer, I will make a point to note that the experimenters still could have gotten this result by random chance alone, so it is technically valid to claim that there isn't enough data to reject the null.

Mostly jokes here, but the point is to shift them away from seeing 0.05 as a magic fixed number, and more of a general idea that tends to be used often.

**Assessment:**

P VALUE: Following this session, students will be given a similar prompt as the dolphin question, where they are to asked to respond to an identical problem but with a different sample size and proportion. Students will then have to calculate the P value given the information at hand.

To avoid different answers that could be falsely marked wrong, students will be introduced to the sim's "infinite sample mode" (the binomial setting) so that everyone has ideal answers.

DELIVERY: IN CLASS PAPER WHICH CAN BE TAKEN HOME AND RETURNED THE FOLLOWING LECTURE. STAKES: MEDIUM HOMEWORK POINTS
