---
title: "syllabus"
---

INSTRUCTOR: Carson Trego, carson.trego\@huslers.unl.edu

CLASS: days:{X, X, X } time{XX:XX}

LOCATION: XXX, X Hall

HELP HOURS: M 12:30P-1:30P, F 12:30P-2:30P

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

IMPORTANT DATES:

Exam1: xx/xx

Exam2: xx/xx

Exam3: xx/xx

Final Project Presentation: xx/xx

Final Project paper due: xx/xx

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

GRADE PORTION:

Exam1: 20%

Exam2: 20%

Final Project: 30%

Homework/participation: 30%

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

HOMEWORK:

To avoid homework from causing any stressful cramming and loss sleep, homework will be cut into small pieces that are assigned and completed for each section completed. This means that you may have more than 1 homework items assigned per week, but they will be very short, and will not be due until the necessary information is taught in class.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

PARTICIPATION:

These are usually given as 100% or 0%. If you are present in class and attempt to participate in the activities, you will get these points.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

SICK/ABSENT POLICY:

Absences will result in a zero in the daily participation points, however, these points can be earned back.

The current policy for earning points back is attending office hours/zoom and explaining the information that you were absent for, and answering a few questions. Once this is considered satisfactory, you will earn a credit for a missed class. You may only do this at a rate of one point back per week.

If a particularly bad illness happens or another difficult circumstances, a doctors note or other relevant form of documentation may be provided and all points will be given back without needing to accomplish a task.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

CALCULATORS

Calculators will be allowed on tests. Graphers are allowed if you register to have your memory cleared 10 minutes before the exam. Once cleared, you will be provided with a sticker showing proof of clearing.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

EXAM STRUCTURE

\@\@ideally i would like to provide tests in way that is proctored yet allows for significant time, but I am currently working out how that would be achieved. I ideal circumstances, I could be a late class that allows students ample time after the scheduled time, but things dont always work out as planned, so I will gather more information before setting this in stone

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

FINAL PROJECT

Rather than a final exam, you will be expected to do a group/solo project where you will be given a practical question to answer using the information that was covered in class. The project will be in three parts: a presentation,paper, and reflection. The presentation will be given during classtimes, and the paper will be submitted a few days after presentations. Attendance and reflections on your own and other classmates projects will be required to receive a full grade.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

ACADEMIC HONESTY

As with all courses, academic dishonesty can potentially result in significant grade reduction and further punishment. If you are suspected of committing academic dishonesty, you will be given a chance to meet and discuss what had happen before facing any punishment.

Students may be randomly asked to casually discuss the answers they have provided on assignments. Being called in does NOT mean that you are being accused of academic dishonesty, and you will be given ample time to collect your thoughts as explaining answers is inherently stressful for many students.

The polices for academic dishonesty will be stated on a per assignment basis, so while it may be allowed to discuss problems with others on one assignment, it may not be allowed for another. In general, copying statements word for word in your answers will NOT be allowed.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

PHOTO POLICY

Students often take photos of the board to save time on notes. These notes will be provided on the canvas website, and any relevant board information will be shared as well. So photos should not be required.

Please do not take pictures in class without permission prior, as many students prefer not to be recorded. If you would like a copy of any information in class, please let me know!

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

SERVICES FOR STUDENTS WITH DISABILITIES

The university provides accommodations for disabilities registered with the Services for Students with Disabilities (SSD). If you are registered with the SSD, please schedule a meeting with me as soon as possible to discuss and plan accommodations.

If you have a disability and are not registered and are concerned about a disability, you can contact the SSD office to discuss accommodation plans.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

ACE OUTCOME 3 (obtained word for word, have questions on this)

"Use mathematical, computational, statistical, or formal reasoning (including reasoning based on princi- ples of logic) to solve problems, draw inferences, and determine reasonableness. The reinforced skills for STAT 218 are writing and critical thinking. STAT 218 will provide the student opportunities to achieve this learning outcome through readings, quizzes, and in-class activities. These assignments (together with exams) will be used by the instructor to assess achievement of the outcome. The final exam will be used by the Department of Statistics to carry out an overall assessment of STAT 218 and the course's effectiveness at assisting students in achieving Outcome 3"

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

DIVERSITY AND INCLUSION

The University of Nebraska-Lincoln does not discriminate on the basis of race, ethnicity, color, national origin, sex (including pregnancy), religion, age, disability, sexual orientation, gender identity, genetic information, veteran status, marital status, and/or political affiliation.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

SUPPORT SERVICES (obtained word for word, have questions on this)

"You can schedule free appointments for individual academic coaching with First-Year Experience and Transition Program staff through MyPLAN. You can also take advantage of study stops--which provide individual and group study with learning consultants in a variety of disciplines--and free group work- shops on topics such as time management, goal setting, test preparation, and reading strategies. See success.unl.edu for schedules and more information."

COUNSELING AND PSYCHOLOGICAL SERVICES

"UNL offers a variety of options to students to aid them in dealing with stress and adversity. Counseling and Psychological & Services (CAPS) is a multidisciplinary team of psychologists and counselors that works collaboratively with Nebraska students to help them explore their feelings and thoughts and learn helpful ways to improve their mental, psychological and emotional well-being when issues arise."

CAPS can be reached by calling 402-472-7450.

"Big Red Resilience & Well-Being (BRRWB) provides one-on-one well-being coaching to any student who wants to enhance their well-being. Trained well-being coaches help students create and be grateful for positive experiences, practice resilience and self-compassion, and find support as they need it. BRRWB can be reached by calling 402-472-8770"
